/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jobdesk;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Userpc
 */
public class frm_job_mon extends javax.swing.JFrame {

    private Crud_Job dat;
    private String username;
    private String idhps;
    private boolean cedit=false;
    private Date tgledit;
    private String jobnum;
    private String pic="";
    private String aprove="";
    private String selesai="";
    private String desc="";
    
    /**
     * Creates new form frm_job_mon
     */
    public frm_job_mon(String username) {

        this.username = username;
        initComponents();
        try {

            dat = new Crud_Job();
            dat.readRecPIC();

        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }

        cmb_pic.setModel(dat.picmodel);
        lbl_tgl_cur.setDate(Getcurdate());
      //  refreshtbl();
        
        //refreshtblxs();
       
        
        txt_username.setText(username);
        
         
        // addMouseListenerRecrusively(lbl_tgl_cur);


    }

//    private void addMouseListenerRecrusively(Container container){
//
//   for (Component component:container.getComponents()){
//     if (component instanceof Container)
//        addMouseListenerRecrusively((Container) component); 
//   }
//
//   container.addMouseListener(new java.awt.event.MouseAdapter() {
//        public void mouseClicked(java.awt.event.MouseEvent evt) {
//            
//            if(evt.getClickCount()==2){
//              int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan di Tgl  ?", "Konfirmasi",
//                   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            }
//            }
//    });
//
//}
    public frm_job_mon() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_mnu = new javax.swing.JPopupMenu();
        mnu_edit = new javax.swing.JMenuItem();
        mnu_delete = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_job_desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cmb_pic = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dt_req = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        dt_target = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txt_finish = new javax.swing.JTextField();
        sp_priorty = new com.toedter.components.JSpinField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_remark = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_save = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        lbl_user = new javax.swing.JLabel();
        lbl_tgl_cur = new com.toedter.calendar.JDateChooser();
        txt_pic = new javax.swing.JTextField();
        dt_req1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_pwd_lama = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_pwd_baru = new javax.swing.JPasswordField();
        bt_save2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dt_cari_creation = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        bt_refresh = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        bt_cetak = new javax.swing.JButton();
        bt_cetak_pertgl = new javax.swing.JButton();

        mnu_edit.setText("Edit");
        mnu_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_editActionPerformed(evt);
            }
        });
        popup_mnu.add(mnu_edit);

        mnu_delete.setText("Delete");
        mnu_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_deleteMouseClicked(evt);
            }
        });
        mnu_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_deleteActionPerformed(evt);
            }
        });
        popup_mnu.add(mnu_delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane2.setName(""); // NOI18N

        jLabel1.setText("Job Description");

        txt_job_desc.setColumns(20);
        txt_job_desc.setLineWrap(true);
        txt_job_desc.setRows(5);
        jScrollPane1.setViewportView(txt_job_desc);

        jLabel2.setText("Pic");

        cmb_pic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_picActionPerformed(evt);
            }
        });

        jLabel3.setText("Request");

        jLabel4.setText("Target");

        jLabel5.setText("Priorty Number");

        jLabel6.setText("Finish");

        txt_remark.setColumns(20);
        txt_remark.setLineWrap(true);
        txt_remark.setRows(5);
        txt_remark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_remarkKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_remark);

        jLabel7.setText("Remark / Status");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_batal.setText("Batal");
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        bt_delete.setText("Delete All");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("User Name :");

        lbl_tgl_cur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tgl_curMouseClicked(evt);
            }
        });
        lbl_tgl_cur.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbl_tgl_curPropertyChange(evt);
            }
        });

        dt_req1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dt_req1MouseReleased(evt);
            }
        });
        dt_req1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dt_req1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sp_priorty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_pic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_finish)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dt_req, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dt_target, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(dt_req1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                    .addComponent(txt_pic, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_batal, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(514, 514, 514))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_tgl_cur, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_user)
                            .addComponent(lbl_tgl_cur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_save)
                            .addComponent(bt_batal)
                            .addComponent(bt_delete)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txt_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dt_req, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dt_target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dt_req1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_finish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sp_priorty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Job Activities", jPanel1);

        jLabel9.setText("User");

        jLabel10.setText("Password Lama");

        txt_username.setEditable(false);

        jLabel11.setText("Password Baru");

        bt_save2.setText("Save");
        bt_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_save2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_lama, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(833, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_save2)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ubah Password", jPanel2);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel12.setText("Status Finish");

        jLabel13.setText("Date Creation");

        dt_cari_creation.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dt_cari_creationPropertyChange(evt);
            }
        });

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Selesai (ok)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Belum Selesai (no)");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        jLabel14.setText("Status Aprove");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Aprove (ok)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Belum Aprove (no)");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        bt_cetak.setText("Cetak Semua");
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });

        bt_cetak_pertgl.setText("Cetak Per Tgl");
        bt_cetak_pertgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetak_pertglActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButton2)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton4))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dt_cari_creation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(bt_cetak_pertgl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton3)
                                .addComponent(jRadioButton4))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dt_cari_creation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt_refresh)
                                .addComponent(bt_cetak)
                                .addComponent(bt_cetak_pertgl)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("List Job Activities", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        try {
            // TODO add your handling code here:

            
            
            if (checktxt()) {
            
             if(!cedit)
             {
                
                dat = new Crud_Job();
                dat.SaveJob(txt_job_desc.getText(), txt_pic.getText(), convertToDate(dt_req.getDate()),
                        convertToDate(dt_target.getDate()), txt_finish.getText(), sp_priorty.getValue(), txt_remark.getText(),
                        "no", "no", lbl_user.getText(),convertToDateF(lbl_tgl_cur.getDate()));

                refreshtbl();

                cls();
             }
             else{
                 dat = new Crud_Job();
//                 dat.updateJobRec(convertToDateE(tgledit),txt_job_desc.getText(), cmb_pic.getSelectedItem().toString(), convertToDate(dt_req.getDate()),
//                        convertToDate(dt_target.getDate()), txt_finish.getText(), sp_priorty.getValue(), txt_remark.getText());
                
                 dat.updateJobRec(jobnum,txt_job_desc.getText(), txt_pic.getText(), convertToDate(dt_req.getDate()),
                        convertToDate(dt_target.getDate()), txt_finish.getText(), sp_priorty.getValue(), txt_remark.getText());
                 
                 refreshtbl();
              }
                
            } else {

                if (sp_priorty.getValue() == 0) {

                    JOptionPane.showMessageDialog(null, "Priorty Number 0");
                } else {
                    JOptionPane.showMessageDialog(null, "Text Ada yang Kosong!");
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }

        //System.out.println(dt_req.getDate().toString());

    }//GEN-LAST:event_bt_saveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lbl_user.setText(username);
        refreshtbl();
        refreshtblxs();
    }//GEN-LAST:event_formWindowOpened

    private void txt_remarkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_remarkKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_save.requestFocus();
        }
    }//GEN-LAST:event_txt_remarkKeyPressed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
        cls();
    }//GEN-LAST:event_bt_batalActionPerformed

    
    
    
private void CekGantiPass(){
    try {
            // TODO add your handling code here:

           // StrPr c = new StrPr();
            
            
            dat = new Crud_Job();
            
            dat.Cek(txt_username.getText());
            
            
            
            if (Crud_Job.usm.equals(txt_username.getText()) && Crud_Job.psm.equals(txt_pwd_lama.getText())) {
                dat = new Crud_Job();
                dat.updateusrRec(txt_username.getText(), txt_pwd_baru.getText());
                  
                
            } else {
                JOptionPane.showMessageDialog(null, "Password atau User Salah!");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
    
    
 private void showPopupMenu(MouseEvent e) {
   popup_mnu.show(this, e.getX(), e.getY());
}
    
    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        
        System.out.println("tes");
        
        if (evt.isPopupTrigger()) {

            int row = jTable1.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {
                popup_mnu.show(jTable1, evt.getX(), evt.getY());
                idhps = (jTable1.getModel().getValueAt(row, 11).toString());
                aprove= (jTable1.getModel().getValueAt(row, 8).toString());
                selesai= (jTable1.getModel().getValueAt(row, 9).toString());
                desc= (jTable1.getModel().getValueAt(row, 1).toString());
                System.out.println(selesai);
            }

        }

    }//GEN-LAST:event_jTable1MouseReleased

    private void mnu_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_deleteMouseClicked
    }//GEN-LAST:event_mnu_deleteMouseClicked

    private void mnu_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_deleteActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan  " + desc + " ?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            try {
                // TODO add your handling code here:
              if(selesai.equals("no")){  
                dat = new Crud_Job();
                dat.DelRec(idhps);
                refreshtbl();
              }
              else{
               JOptionPane.showMessageDialog(null, "Tidak Bisa dihapus Karena Sudah Selesai!");
              }
            } catch (Exception ex) {
                Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_mnu_deleteActionPerformed

    private void lbl_tgl_curMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tgl_curMouseClicked
        // TODO add your handling code here:
        // if (evt.getClickCount() == 2) {
//         lbl_tgl_cur.addPropertyChangeListener("calendar", new PropertyChangeListener() {
//                public void propertyChange(PropertyChangeEvent e) {
//                       int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan di Tgl  ?", "Konfirmasi",
//                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//                }
//            });
        //}
    }//GEN-LAST:event_lbl_tgl_curMouseClicked

    private void lbl_tgl_curPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbl_tgl_curPropertyChange
        // TODO add your handling code here:
        if (lbl_tgl_cur.getDate() != null) {
            refreshtbl();
        }

//         int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Pekerjaan di Tgl  ?", "Konfirmasi",
//                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        System.out.println("tgl");
    }//GEN-LAST:event_lbl_tgl_curPropertyChange

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        try {
            // TODO add your handling code here:
            int response = JOptionPane.showConfirmDialog(null, "Apakah Akan di hapus Semua Pekerjaan di Tgl " + convertToDateF(lbl_tgl_cur.getDate()) + "?", "Konfirmasi",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {
                try {
                    // TODO add your handling code here:
                    
                    dat = new Crud_Job();
                    dat.DelRecAll(convertToDateF(lbl_tgl_cur.getDate()),lbl_user.getText());
                    refreshtbl();
                 
                    
                } catch (Exception ex) {
                    Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bt_deleteActionPerformed

    private void mnu_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_editActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            // No row selected
        } else {

            try {
                
            if(selesai.equals("no"))    {
                cedit=true;
                
                txt_job_desc.setText(jTable1.getModel().getValueAt(row, 1).toString());
                txt_pic.setText(jTable1.getModel().getValueAt(row, 2).toString());
                dt_req.setDate(ConvStrToDate(jTable1.getModel().getValueAt(row, 3).toString()));
                dt_target.setDate(ConvStrToDate(jTable1.getModel().getValueAt(row, 4).toString()));
                txt_finish.setText(jTable1.getModel().getValueAt(row, 5).toString());
                sp_priorty.setValue(Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString()));
                txt_remark.setText(jTable1.getModel().getValueAt(row, 7).toString());
                tgledit= convertToDateEx(jTable1.getModel().getValueAt(row, 10).toString()) ;
                jobnum=jTable1.getModel().getValueAt(row, 11).toString() ;
                System.out.println("edit tgl: "+tgledit);
            }
            else{
                JOptionPane.showMessageDialog(null, "Tidak Dapat Di Edit Karena Pekerjaan Tersebut sudah selesai!");
            }
            } catch (ParseException ex) {
                Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

    }//GEN-LAST:event_mnu_editActionPerformed

    private void getTblVal(){
    
         int row = jTable1.getSelectedRow();

        if (row == -1) {
            // No row selected
        } else {

           
               
                
                txt_job_desc.setText(jTable1.getModel().getValueAt(row, 1).toString());
                txt_pic.setText(jTable1.getModel().getValueAt(row, 2).toString());
                dt_req.setDate(ConvStrToDate(jTable1.getModel().getValueAt(row, 3).toString()));
                dt_target.setDate(ConvStrToDate(jTable1.getModel().getValueAt(row, 4).toString()));
                txt_finish.setText(jTable1.getModel().getValueAt(row, 5).toString());
                sp_priorty.setValue(Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString()));
                txt_remark.setText(jTable1.getModel().getValueAt(row, 7).toString());
              
               
              
           
        }
    }
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMousePressed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        
        if(evt.getClickCount()==2){
                getTblVal();
        }
        
        
          if (evt.isPopupTrigger()) {
            int row = jTable1.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {
                popup_mnu.show(jTable1, evt.getX(), evt.getY());
                idhps = (jTable1.getModel().getValueAt(row, 11).toString());
                aprove= (jTable1.getModel().getValueAt(row, 8).toString());
                selesai= (jTable1.getModel().getValueAt(row, 9).toString());
                desc= (jTable1.getModel().getValueAt(row, 1).toString());
                System.out.println("aprove: "+selesai);
            }

        }

    }//GEN-LAST:event_jTable1MousePressed

    private void dt_cari_creationPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dt_cari_creationPropertyChange
        // TODO add your handling code here:
         if (dt_cari_creation.getDate() != null) {
            refreshtblx();
        }
    }//GEN-LAST:event_dt_cari_creationPropertyChange

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:
        refreshtblxs();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("no",lbl_user.getText(), 0);
             jTable2.setModel(dat.model);
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("ok",lbl_user.getText(), 0);
            jTable2.setModel(dat.model);
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("ok",lbl_user.getText(),1);
            jTable2.setModel(dat.model);
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            dat=new Crud_Job();
            dat.readRecStat("no",lbl_user.getText(),1);
            jTable2.setModel(dat.model);
            
        } catch (Exception ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void bt_save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save2ActionPerformed
        // TODO add your handling code here:
       if(!txt_pwd_baru.getText().isEmpty()&&!txt_pwd_lama.getText().isEmpty()){ 
            CekGantiPass();
       }
       else{
           
       }
    }//GEN-LAST:event_bt_save2ActionPerformed

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed
        // TODO add your handling code here:
      
     //if(dt_cari_creation.getDate()!=null)  { 
        try {
            dat = new Crud_Job();

            dat.CetakAll(lbl_user.getText());

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }
     //}
  //   else{
     
  //   JOptionPane.showMessageDialog(null, "Tanggal Pencarian Kosong!");
   //  }
    }//GEN-LAST:event_bt_cetakActionPerformed

    private void bt_cetak_pertglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetak_pertglActionPerformed
        // TODO add your handling code here:
        
       // convertToDateF
       
        
         if(dt_cari_creation.getDate()!=null)  { 
        try {
            dat = new Crud_Job();

             dat.CetakPerTgl(convertToDateF(dt_cari_creation.getDate()),lbl_user.getText());

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }
     }
     else{
     
     JOptionPane.showMessageDialog(null, "Tanggal Pencarian Kosong!");
     }
        
        
    }//GEN-LAST:event_bt_cetak_pertglActionPerformed

    private void cmb_picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_picActionPerformed
        // TODO add your handling code here:
        
        pic=pic+cmb_pic.getSelectedItem().toString()+" ";
        
        txt_pic.setText(pic);
    }//GEN-LAST:event_cmb_picActionPerformed

    private void dt_req1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dt_req1MouseReleased
        
    }//GEN-LAST:event_dt_req1MouseReleased

    private void dt_req1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dt_req1PropertyChange
        // TODO add your handling code here:
      if(dt_req1.getDate()!=null)  {
        try {
            // TODO add your handling code here:
            txt_finish.setText(convertToDate(dt_req1.getDate()));
        } catch (ParseException ex) {
            Logger.getLogger(frm_job_mon.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    }//GEN-LAST:event_dt_req1PropertyChange

    private Date ConvStrToDate(String tgl) {


        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date tglt = null;
        try {
            tglt = df.parse(tgl);

        } catch (ParseException e) {
            e.printStackTrace();
        }

        return tglt;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_job_mon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_job_mon().setVisible(true);
            }
        });

    }

    public void refreshtbl() {

        try {
            dat = new Crud_Job();

            dat.readRec(convertToDateF(lbl_tgl_cur.getDate()),lbl_user.getText());
            pic="";
        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        jTable1.setModel(dat.model);
    }

    
    public void refreshtblx() {

        try {
            dat = new Crud_Job();

            dat.readRec(convertToDateF(dt_cari_creation.getDate()),lbl_user.getText());

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        jTable2.setModel(dat.model);
    }

    public void refreshtblxs() {

        try {
            dat = new Crud_Job();

            dat.readRec(lbl_user.getText());

        } catch (Exception e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        jTable2.setModel(dat.model);
    }

    
    private Date Getcurdate() {

        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

        Date date = new Date();

        //dateFormat.format(date)

        return date;
    }

    private String convertToDateF(Date receivedDate) throws ParseException {
//HH:mm:ss
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }

    private String convertToDateE(Date receivedDate) throws ParseException {

        // SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }
    
    private Date convertToDateEx(String receivedDate) throws ParseException {

        //SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

        Date strDate = formatter.parse(receivedDate);

        return strDate;
    }
    
    
    private String convertToDate(Date receivedDate) throws ParseException {

        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");

        String strDate = formatter.format(receivedDate);

        return strDate;
    }

    private boolean checktxt() {

        boolean ck = false;

//        if ((txt_job_desc.getText().isEmpty()
//                && cmb_pic.getSelectedItem().toString().isEmpty()
//                && dt_req.getDate().toString().isEmpty()
//                && dt_target.getDate().toString().isEmpty() && txt_finish.getText().isEmpty()
//                && String.valueOf(sp_priorty.getValue()).isEmpty())) {
//            ck = true;
//
//        }
//booleatn g=dt_req.getDate().toString().isEmpty();
        if (dt_req.getDate() != null && dt_target.getDate() != null && sp_priorty.getValue() != 0
                && !txt_job_desc.getText().isEmpty() && !txt_finish.getText().isEmpty()&& !txt_pic.getText().isEmpty()) {
            ck = true;

        }

        return ck;
    }

    private void cls() {



        for (Component c : jPanel1.getComponents()) {


            if (c instanceof JTextComponent) {
                ((JTextComponent) c).setText("");
            }
        }

        sp_priorty.setValue(0);

        jobnum="";
        pic="";
        dt_req.setDate(null);
        dt_target.setDate(null);
        txt_job_desc.setText("");
        txt_remark.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cetak;
    private javax.swing.JButton bt_cetak_pertgl;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton bt_save;
    private javax.swing.JButton bt_save2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmb_pic;
    private com.toedter.calendar.JDateChooser dt_cari_creation;
    private com.toedter.calendar.JDateChooser dt_req;
    private com.toedter.calendar.JDateChooser dt_req1;
    private com.toedter.calendar.JDateChooser dt_target;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser lbl_tgl_cur;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JMenuItem mnu_delete;
    private javax.swing.JMenuItem mnu_edit;
    private javax.swing.JPopupMenu popup_mnu;
    private com.toedter.components.JSpinField sp_priorty;
    private javax.swing.JTextField txt_finish;
    private javax.swing.JTextArea txt_job_desc;
    private javax.swing.JTextField txt_pic;
    private javax.swing.JPasswordField txt_pwd_baru;
    private javax.swing.JPasswordField txt_pwd_lama;
    private javax.swing.JTextArea txt_remark;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
